language: ruby

rvm:
  - 2.2.3
  - 2.3.3
  - ruby-head
  - rbx

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx

before_install:
  - gem install bundler
  - bundle install --path vendor/bundle

script:
  - bundle exec rspec
